spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: 123456789
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: 5aee0e1b-51f7-414b-908b-c773f389b047
        cluster-name: BEIJING
    sentinel:
      filter:
        url-patterns: /**
#        暂时打开对 Sping MVC 端点的保护
        enabled: true
      transport:
#        指定控制台sentinel的地址
        dashboard: localhost:8080
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations : classpath:/mapper/**Mapper.xml
server:
  port: 8090
#细粒化配置
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
#    对user-center饥饿加载
    clients: user-center
logging:
  level:
    com.cloud : debug
    com.cloud.contentcenter.feignclient.UserCenterFeignClient : debug
feign:
  sentinel:
#    为Feign整合sentinel
    enabled: true
  client:
    config:
#      user-center:
       default:
        loggerLevel: basic
  httpclient:
    enabled: false
    max-connections: 200
    max-connections-per-route: 50
  okhttp:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
#resttemplate:
#  sentinel:
#    enabled: false
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
#    必须指定group
    group: test-group
