spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: 123456789
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: content-center
mybatis:
  mapper-locations : classpath:/mapper/**Mapper.xml
server:
  port: 8090
#细粒化配置
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule